config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'
  get 'errors/unacceptable'
  get 'errors/internal_error'
  devise_for :users

  resources :activities, only: [:index, :new, :create, :destroy, :edit, :update] do
    resource :bookmark, only: [:show, :create]
  end

  resources :categories, only: [:index] do
    resources :activities, only: [:show]
  end
  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end
  resource :dashboard, only: [:show]

  resource :bookmark, only: [:destroy]

  get "dashboard", to: "dashboards#show"
  # get "bookmark", to: "dashboards#show"
  get "/activities/:id" => "activities#destroy"

  devise_scope :user do
   get '/users/sign_out' => 'devise/sessions#destroy'
end

  root to: 'pages#home'

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer-basic">
            <div class="social"><a href="https://www.instagram.com/lewagonmelbourne/?hl=en"><i class="icon ion-social-instagram"></i></a><a href="https://github.com/Shivika-S/ToGather"><i class="icon ion-social-github"></i></a><a href="https://twitter.com/LeWagonMEL?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor"><i class="icon ion-social-twitter"></i></a><a href="https://www.facebook.com/lewagonaustralia/"><i class="icon ion-social-facebook"></i></a></div>
            <p class="copyright">ToGather © 2021</p>
</div>

app/views/shared/_navbar.html.erb
<div id="main-navbar" class="navbar navbar-expand-sm navbar-light navbar-logo">
  <div>
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag('3.png') %>
    <% end %>
  </div>

  <div class="d-flex justify-content collapse" id="navbarSupportedContent">
    <ul class="navbar-nav">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Create an event", new_activity_path, class: "nav-link" %>
        </li>
        <li class= "d-flex nav-item active mr-3">
          <%= link_to "Dashboard", dashboard_path, class: "nav-link" %>
          <%= link_to("Messages", chatroom_path(current_user.chatrooms.first), class: "nav-link") if current_user.chatrooms.count >= 1 %>
          <%= link_to("Messages", "#", class: "nav-link", disabled: true) if current_user.chatrooms.empty? %>
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
      <% else %>
        <li class="nav-item">
          <%= link_to "Create an event", new_activity_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>