config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'
  get 'errors/unacceptable'
  get 'errors/internal_error'
  devise_for :users

  resources :activities, only: [:index, :new, :create, :destroy, :edit, :update] do
    resource :bookmark, only: [:show, :create]
  end

  resources :categories, only: [:index] do
    resources :activities, only: [:show]
  end
  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end
  resource :dashboard, only: [:show]

  resource :bookmark, only: [:destroy]

  get "dashboard", to: "dashboards#show"
  # get "bookmark", to: "dashboards#show"
  get "/activities/:id" => "activities#destroy"

  devise_scope :user do
   get '/users/sign_out' => 'devise/sessions#destroy'
end

  root to: 'pages#home'

end

app/views/pages/about.html.erb
about.html.erb

app/views/pages/home.html.erb
<div class="home-page">
  <div class="banner-cards">
    <div class="banner-card rellax" data-rellax-speed="5" style="background-image: linear-gradient(rgba(0,0,0,0.2), rgba(0,0,0,0.2)), url(https://images.unsplash.com/photo-1511988617509-a57c8a288659?ixid=MXwxMjA3fDB8MHxzZWFyY2h8MTh8fGhhcHB5fGVufDB8fDB8&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60)">
    </div>

    <div class="banner-card rellax" data-rellax-speed="6" style="background-image: linear-gradient(rgba(0,0,0,0.2), rgba(0,0,0,0.2)), url(https://images.unsplash.com/photo-1464692805480-a69dfaafdb0d?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxzZWFyY2h8Mjl8fGhhcHB5fGVufDB8fDB8&auto=format&fit=crop&w=800&q=60)">
    </div>

    <div class="banner-card rellax" data-rellax-speed="7" style="background-image: linear-gradient(rgba(0,0,0,0.2), rgba(0,0,0,0.2)), url(https://images.unsplash.com/photo-1591035897819-f4bdf739f446?ixid=MXwxMjA3fDB8MHxzZWFyY2h8Mjh8fGhhcHB5fGVufDB8fDB8&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60)">
    </div>

    <div class="banner-card rellax" data-rellax-speed="8" style="background-image: linear-gradient(rgba(0,0,0,0.2), rgba(0,0,0,0.2)), url(https://images.unsplash.com/photo-1514845505178-849cebf1a91d?ixid=MXwxMjA3fDB8MHxzZWFyY2h8NTd8fGhhcHB5fGVufDB8fDB8&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60)">
    </div>

    <div class="banner-card rellax" data-rellax-speed="9" style="background-image: linear-gradient(rgba(0,0,0,0.2), rgba(0,0,0,0.2)), url(https://images.unsplash.com/photo-1471286174890-9c112ffca5b4?ixid=MXwxMjA3fDB8MHxzZWFyY2h8MTE5fHxoYXBweXxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60)">
    </div>

    <div class="banner-card rellax" data-rellax-speed="10" style="background-image:linear-gradient(rgba(0,0,0,0.2), rgba(0,0,0,0.2)),  url(https://images.unsplash.com/photo-1502781252888-9143ba7f074e?ixid=MXwxMjA3fDB8MHxzZWFyY2h8MzJ8fGhhcHB5fGVufDB8fDB8&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60)">
    </div>

    <div class="banner-card rellax" data-rellax-speed="4" style="background-image: linear-gradient(rgba(0,0,0,0.2), rgba(0,0,0,0.2)), url(https://images.unsplash.com/photo-1506956191951-7a88da4435e5?ixid=MXwxMjA3fDB8MHxzZWFyY2h8MTU0fHxoYXBweXxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60)">
    </div>

    <div class="banner-card rellax" data-rellax-speed="5" style="background-image: linear-gradient(rgba(0,0,0,0.2), rgba(0,0,0,0.2)), url(https://images.unsplash.com/photo-1505224959304-f6daf7fd0559?ixid=MXwxMjA3fDB8MHxzZWFyY2h8MTU1fHxoYXBweXxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60)">
    </div>

    <div class="banner-card rellax" data-rellax-speed="6" style="background-image: linear-gradient(rgba(0,0,0,0.2), rgba(0,0,0,0.2)), url(https://images.unsplash.com/photo-1519671482749-fd09be7ccebf?ixid=MXwxMjA3fDB8MHxzZWFyY2h8MTUwfHxoYXBweXxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60)">
    </div>

    <div class="banner-card rellax" data-rellax-speed="7" style="background-image: linear-gradient(rgba(0,0,0,0.2), rgba(0,0,0,0.2)), url(https://images.unsplash.com/photo-1607748725046-cd194b716604?ixid=MXwxMjA3fDB8MHxzZWFyY2h8MjIxfHxoYXBweXxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60)">
    </div>

    <div class="banner-card rellax" data-rellax-speed="8" style="background-image: linear-gradient(rgba(0,0,0,0.2), rgba(0,0,0,0.2)), url(https://images.unsplash.com/photo-1467307983825-619715426c70?ixid=MXwxMjA3fDB8MHxzZWFyY2h8MTYxfHxoYXBweXxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60)">
    </div>

    <div class="banner-card rellax" data-rellax-speed="9" style="background-image: linear-gradient(rgba(0,0,0,0.2), rgba(0,0,0,0.2)), url(https://images.unsplash.com/photo-1591035898858-1df97bccf2ae?ixid=MXwxMjA3fDB8MHxzZWFyY2h8MjI3fHxoYXBweXxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60)">
    </div>

    <div class="banner-card rellax" data-rellax-speed="3" style="background-image: linear-gradient(rgba(0,0,0,0.2), rgba(0,0,0,0.2)), url(https://images.unsplash.com/photo-1590368294028-638eff648ffa?ixid=MXwxMjA3fDB8MHxzZWFyY2h8MjI2fHxoYXBweXxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60)">
    </div>

    <div class="banner-card rellax" data-rellax-speed="4" style="background-image: linear-gradient(rgba(0,0,0,0.2), rgba(0,0,0,0.2)), url(https://images.unsplash.com/photo-1595650248893-df56f2066e04?ixid=MXwxMjA3fDB8MHxzZWFyY2h8MjMxfHxoYXBweXxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60)">
    </div>

    <div class="banner-card rellax" data-rellax-speed="5" style="background-image: linear-gradient(rgba(0,0,0,0.2), rgba(0,0,0,0.2)), url(https://images.unsplash.com/photo-1591793923188-d1ebb8086f62?ixid=MXwxMjA3fDB8MHxzZWFyY2h8MjM2fHxoYXBweXxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60)">
    </div>

    <div class="banner-card rellax" data-rellax-speed="6" style="background-image: linear-gradient(rgba(0,0,0,0.2), rgba(0,0,0,0.2)), url(https://images.unsplash.com/photo-1610173827002-62c0f1f05d04?ixid=MXwxMjA3fDB8MHxzZWFyY2h8Mjc3fHxoYXBweXxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60)">
    </div>

    <div class="banner-card rellax" data-rellax-speed="7" style="background-image: linear-gradient(rgba(0,0,0,0.2), rgba(0,0,0,0.2)), url(https://images.unsplash.com/photo-1596510915124-38eaa5517966?ixid=MXwxMjA3fDB8MHxzZWFyY2h8Mjg5fHxoYXBweXxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60)">
    </div>

    <div class="banner-card rellax" data-rellax-speed="8" style="background-image: linear-gradient(rgba(0,0,0,0.2), rgba(0,0,0,0.2)), url(https://images.unsplash.com/photo-1486704155675-e4c07f8ad160?ixid=MXwxMjA3fDB8MHxzZWFyY2h8Mjk0fHxoYXBweXxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60)">
    </div>

    <div class="banner-card rellax" data-rellax-speed="2" style="background-image: linear-gradient(rgba(0,0,0,0.2), rgba(0,0,0,0.2)), url(https://images.unsplash.com/photo-1480866179948-2caa74d9082a?ixid=MXwxMjA3fDB8MHxzZWFyY2h8Mjk1fHxoYXBweXxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60)">
    </div>

    <div class="banner-card rellax" data-rellax-speed="3" style="background-image: linear-gradient(rgba(0,0,0,0.2), rgba(0,0,0,0.2)), url(https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?ixid=MXwxMjA3fDB8MHxzZWFyY2h8MzEwfHxoYXBweXxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60)">
    </div>

    <div class="banner-card rellax" data-rellax-speed="4" style="background-image: linear-gradient(rgba(0,0,0,0.2), rgba(0,0,0,0.2)), url(https://images.unsplash.com/photo-1529008475023-5d5271a6fe50?ixid=MXwxMjA3fDB8MHxzZWFyY2h8MzI1fHxoYXBweXxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60)">
    </div>

    <div class="banner-card rellax" data-rellax-speed="5" style="background-image: linear-gradient(rgba(0,0,0,0.2), rgba(0,0,0,0.2)), url(https://images.unsplash.com/photo-1508461235343-942692734024?ixid=MXwxMjA3fDB8MHxzZWFyY2h8MzYxfHxoYXBweXxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60)">
    </div>

    <div class="banner-card rellax" data-rellax-speed="6" style="background-image: linear-gradient(rgba(0,0,0,0.2), rgba(0,0,0,0.2)), url(https://images.unsplash.com/photo-1492462543947-040389c4a66c?ixid=MXwxMjA3fDB8MHxzZWFyY2h8MzIwfHxoYXBweXxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60)">
    </div>

    <div class="banner-card rellax" data-rellax-speed="7" style="background-image: linear-gradient(rgba(0,0,0,0.2), rgba(0,0,0,0.2)), url(https://images.unsplash.com/photo-1517981834318-5f56734fe518?ixid=MXwxMjA3fDB8MHxzZWFyY2h8MzIxfHxoYXBweXxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60)">
    </div>
  </div>
  <div class="banner-call">
    <div class="banner-question-category">
      <div class="title-and-call">
        <div class="container">
          <h1 id="home-title" class="rellax" data-rellax-speed="4">ToGather</h1>
        </div>
        <div class="container">
          <div class="banner-question">
            <button class="home-init-button js-home-init-btn rellax" data-rellax-speed="1">Lets get togather</button>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="category-form-container">
  <!--   <div class="filler-div"></div> -->
    <%= simple_form_for @activity, method: :get do |f| %>
      <div class="banner-question-category js-home-category-question d-flex justify-content-center align-items-center">
        <div class="question-category-container">
          <div id="banner-question-category-header">
            <h1>What are you in the mood for?</h1>
          </div>
          <div class="category-buttons">
            <%= f.input :category_id, as: :radio_buttons, collection: Category.all, :item_wrapper_class => 'inline', label: false, :label_method => :name,:value_method => :id, include_blank: false, label_html: { class: "homepage-categories" }  %>
          </div>
        </div>
      </div>
      <div class="banner-question-date js-home-date-question d-flex flex-column justify-content-center align-items-center">
        <h1 id="banner-question-date-header">Which date do you fancy?</h1>
        <div class="container d-flex justify-content-center">
          <div class="date-buttons">
            <%# f.date_field :start_time %>
            <%= f.input :start_time, as: :date, label: false, class: "text-right" %>
            <%= f.submit "Find me something to do!", class: "btn btn-primary", id: "form-search-button" %>
            <div id="autotype-day"><p></p></div>
            <div id="autotype-month"><p></p></div>
            <div id="autotype-year"><p></p></div>
            <div id="arrow-day-date" style="background-image: url(https://cdn4.iconfinder.com/data/icons/hand-drawn-arrows/100/hand_drawn_arrows-18-512.png)"></div>
            <div id="arrow-day-month" style="background-image: url(https://cdn4.iconfinder.com/data/icons/hand-drawn-arrows/100/hand_drawn_arrows-18-512.png)"></div>
            <div id="arrow-day-year" style="background-image: url(https://cdn4.iconfinder.com/data/icons/hand-drawn-arrows/100/hand_drawn_arrows-18-512.png)"></div>
          </div>
        </div>
        <div class="tree-image"></div>
        <div class="sun-image"></div>
        <div class="dumbbell-image"></div>
        <div class="mario-image"></div>
        <div class="mario-two-image"></div>
      </div>
    <% end %>

  </div>
</div>
<!-- <div>
  <h2> Pick a mood</h2>
<% @categories.each do |category| %>
<%# link_to category.name, new_category_activity_path(category), class: "btn btn-primary" %>
<% end %>
</div> -->