config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'
  get 'errors/unacceptable'
  get 'errors/internal_error'
  devise_for :users

  resources :activities, only: [:index, :new, :create, :destroy, :edit, :update] do
    resource :bookmark, only: [:show, :create]
  end

  resources :categories, only: [:index] do
    resources :activities, only: [:show]
  end
  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end
  resource :dashboard, only: [:show]

  resource :bookmark, only: [:destroy]

  get "dashboard", to: "dashboards#show"
  # get "bookmark", to: "dashboards#show"
  get "/activities/:id" => "activities#destroy"

  devise_scope :user do
   get '/users/sign_out' => 'devise/sessions#destroy'
end

  root to: 'pages#home'

end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def show
    @bookmarks = current_user.bookmarks
    @activities = current_user.activities
  end
end

app/views/dashboards/show.html.erb
<div class="container">
  <br>
  <h1>My Dashboard</h1>
  <br>

  <ul class="nav nav-tabs" id="myTab" role="tablist">
    <li class="nav-item">
      <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">Bookmarks</a>
    </li>
      <li class="nav-item">
        <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">Activities</a>
    </li>
  </ul>

  <div class="tab-content" id="myTabContent">
    <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
      <% @bookmarks.each do |bookmark| %>
      <% end %>
      <div class="dashboard-cards-container">
        <div class ="dashboard-cards">
          <% @bookmarks.each do |bookmark| %>
            <% activity = bookmark.activity %>
            <div class="activity-card">
              <%= link_to category_activity_path(:category_id, activity) do %>
                <% if activity.cover_photo.attached? %>
                  <div class="image-container">
                    <%= cl_image_tag(activity.cover_photo.key,
                      class: "dashboard-card-images", height: 300, fit: :clip) %>
                  </div>
                <% end %>
                <div class="image-buttons" id="image-name">
                  <h5><strong><%= activity.name %></strong></h5>
                  <%= link_to "delete", bookmark_path(bookmark), method: :delete, data: { confirm: "Are you sure you want to delete your activity?"}, class: "btn btn-danger" %>
                </div>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>

    <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
      <% if @activities.exists? %>
      <% end %>

      <div class="dashboard-cards-container">
        <div class ="dashboard-cards">
          <% @activities.each do |activity| %>
            <div class="activity-card">
              <%= link_to category_activity_path(:category_id, activity) do %>
                <% if activity.cover_photo.attached? %>
                  <div class="image-container">
                    <%= cl_image_tag(activity.cover_photo.key,
                      class: "dashboard-card-images", height: 300, fit: :clip) %>
                  </div>
                <% end %>
                <% if activity.user == current_user %>
                  <div class="image-buttons" id="image-name">
                    <h5><strong><%= activity.name %></strong></h5>
                  </div>
                  <div class="image-buttons" id="dashboard-buttons">
                    <%= link_to 'Edit', edit_activity_path(activity), class: "btn btn-warning" %>
                    </div>
                    <div class="image-buttons" id="second-button">
                    <%= link_to 'Delete', activity_path(activity.id), method: :delete, data: { confirm: "Are you sure you want to delete your activity?"}, class: "btn btn-danger" %>
                  </div>
                <% end %>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>