config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'
  get 'errors/unacceptable'
  get 'errors/internal_error'
  devise_for :users

  resources :activities, only: [:index, :new, :create, :destroy, :edit, :update] do
    resource :bookmark, only: [:show, :create]
  end

  resources :categories, only: [:index] do
    resources :activities, only: [:show]
  end
  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end
  resource :dashboard, only: [:show]

  resource :bookmark, only: [:destroy]

  get "dashboard", to: "dashboards#show"
  # get "bookmark", to: "dashboards#show"
  get "/activities/:id" => "activities#destroy"

  devise_scope :user do
   get '/users/sign_out' => 'devise/sessions#destroy'
end

  root to: 'pages#home'

end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :category
  belongs_to :user, optional: true
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  has_one_attached :cover_photo
  has_many_attached :photos
  has_many :bookmarks, dependent: :destroy
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show, :new, :create, :destroy]
  before_action :set_activity, only: [:show, :edit, :update, :destroy]

  def index
    if activity_params[:category_id]
      @start_time = format_datetime
      @category = Category.find(params[:activity][:category_id]) if params[:activity][:category_id].present?
      @activities = Activity.where(category: @category)
      @activities = @activities.where("start_time > ?", @start_time)
    else
      @activities = Activity.all
    end
    params[:activity].nil? ? @activity = Activity.new : @activity = Activity.new(activity_params)
  end

  def show
    @markers = [{
      lat: @activity.latitude,
      lng: @activity.longitude,
      infoWindow: render_to_string(partial: "info_window", locals: { activity: @activity }),
      image_url: helpers.asset_url('placeholder.png')
    }]
    # @chatroom will be set to nil if no chat room with same name as activity exist
    @chatroom = Chatroom.find_by(name: @activity.name)
    # ||= will only set to value if @chatroom is nil
    @chatroom ||= Chatroom.create!(name: @activity.name)
  end

  def new
    @activity = Activity.new
  end

  def create
    @activity = Activity.new(activity_params)
    @activity.category = Category.find(params[:activity][:category])
    @activity.user = current_user
    if @activity.save
      redirect_to category_activity_path(@activity.category, @activity)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @activity.update(activity_params)
      redirect_to dashboard_path
    else
      render :edit
    end
  end

  def destroy
    @activity.destroy
    redirect_to dashboard_path, :notice => "Your Activity has been deleted"
  end

  private

  def set_activity
    @activity = Activity.find(params[:id])
  end

  def format_datetime
    if params[:activity]['start_time(1i)'] && params[:activity]['start_time(2i)'] && params[:activity]['start_time(3i)']
      date_str = "#{params[:activity]['start_time(1i)']}-#{params[:activity]['start_time(2i)']}-#{params[:activity]['start_time(3i)']}"
    elsif params[:activity][:start_time]
      date_str = params[:activity][:start_time]
    end
    utc_datetime = Date.parse(date_str).to_datetime
    utc_datetime.in_time_zone('Australia/Melbourne') # could add timezone to user and access current_user.timezone here
    # user_date = utc_date.in_time_zone(time_zone)
  end

  # def activities_on_day(activities, date)
  #   activities = activities.where(:start_time => date.beginning_of_day..date.end_of_day)
  # end

  def activity_params
    params.require(:activity).permit(:name, :start_time, :address, :description, :category_id, :cover_photo, photos: [])
  end
end

app/views/activities/_info_window.html.erb
<h2><%= activity.name %></h2>
<p><%= activity.address %></p>

app/views/activities/edit.html.erb
<div class="container">
  <h1>Update your activity</h1>

  <%= simple_form_for [ @activity ] do |f| %>
    <%= f.input :category, as: :select, collection: Category.all, prompt: 'Select a category', label: false %>
    <%= f.input :name %>
    <%= f.input :start_time, as: :date %>
    <%= f.input :cover_photo, as: :file %>
    <%= f.input :photos, as: :file, input_html: { multiple: true } %>
    <%= f.submit "Update", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/activities/index.html.erb
<div class="container index-search-container d-flex">

  <%= simple_form_for @activity, method: :get, html: {novalidate: true, class: "no-bs-validation"} do |f| %>
    <div class="index-search-components">
      <div class="mr-3">
        <%= f.association :category, label_method: :name, label: false, prompt: "Select category" %>
      </div>
      <div>
        <%= f.date_field :start_time %>
      </div>
      <div>
        <%= f.submit "Find me something to do!", class: "btn btn-primary", id: "form-search-button" %>
      </div>
    </div>
  <% end %>
</div>

<div class="container">
  <div class="card-columns">
    <% @activities.each do |activity| %>
      <div class="card"  data-toggle="modal" data-target=".js-activity-<%= activity.id %>">
        <div class="bookmark-buttons">
          <% if current_user %>
            <%# unless current_user.bookmarks.where(activity_id: activity.id).empty? %>
              <%# link_to 'Saved', bookmark_path(current_user.bookmarks.first), method: :delete, class: "index-save-btn btn btn-secondary" %>
            <%# else %>
              <%# link_to 'Save', activity_bookmark_path(activity_id: activity.id), method: :post, class: "index-save-btn btn btn-outline-secondary" %>
            <%# end %>

            <!-- Temp button since the above bookmark function doesn't link correctly -->

            <button type="button" class="index-save-btn btn btn-outline-secondary">Save</button>

          <% else %>
            <button type="button" class="index-save-btn btn btn-outline-secondary">Save</button>
          <% end %>
        </div>
          <% if activity.cover_photo.attached? %>
            <%= cl_image_tag(activity.cover_photo.key,
              class: "card-images", height: 300, fit: :clip) %>
          <% end %>
          <div id="card_details">
            <h5><%= activity.name %></h5>
            <p class="mb-3"><%= activity.description %></p>
            <% if @start_time == activity.start_time %>
              <button class="btn btn-outline-danger">Today</button>
            <% end %>
          </div>
        </div>

        <!-- Modal -->
        <div class="modal fade js-activity-<%= activity.id %>" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
          <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
            <div class="modal-content" style="border-radius: 10px;">
              <div class="modal-body" id="body-of-modal">
                <div class="d-flex justify-content-center align-items-center">
                  <div id="js-carousel-indicators-<%= activity.id %>" class="carousel slide" data-ride="carousel">
                    <ol class="carousel-indicators">
                      <% if activity.photos[2] %>
                        <li data-target="#js-carousel-indicators-<%= activity.id %>" data-slide-to="0" class="active"></li>
                        <li data-target="#js-carousel-indicators-<%= activity.id %>" data-slide-to="1"></li>
                        <li data-target="#js-carousel-indicators-<%= activity.id %>" data-slide-to="2"></li>
                        <li data-target="#js-carousel-indicators-<%= activity.id %>" data-slide-to="3"></li>
                      <% elsif activity.photos[1] %>
                        <li data-target="#js-carousel-indicators-<%= activity.id %>" data-slide-to="0" class="active"></li>
                        <li data-target="#js-carousel-indicators-<%= activity.id %>" data-slide-to="1"></li>
                        <li data-target="#js-carousel-indicators-<%= activity.id %>" data-slide-to="2"></li>
                        <% elsif activity.photos[0] %>
                        <li data-target="#js-carousel-indicators-<%= activity.id %>" data-slide-to="0" class="active"></li>
                        <li data-target="#js-carousel-indicators-<%= activity.id %>" data-slide-to="1"></li>
                      <% end %>
                    </ol>
                      <div class="carousel-inner">
                        <% if activity.cover_photo.attached? %>
                          <div class="carousel-item active">
                            <img class="carousel-pic" src=<%= cl_image_path(activity.cover_photo.key,
                              height: 200) %> alt="#">
                          </div>
                        <% end %>
                        <% if activity.photos[0] %>
                          <div class="carousel-item">
                            <img class="carousel-pic" src=<%= cl_image_path(activity.photos[0].key,
                              height: 200) %> alt="#">
                          </div>
                        <% end %>
                        <% if activity.photos[1] %>
                          <div class="carousel-item">
                            <img class="carousel-pic" src=<%= cl_image_path(activity.photos[1].key,
                              height: 200) %> alt="#">
                          </div>
                        <% end %>
                        <% if activity.photos[2] %>
                          <div class="carousel-item">
                            <img class="carousel-pic" src=<%= cl_image_path(activity.photos[2].key,
                              height: 200) %> alt="#">
                          </div>
                        <% end %>
                      </div>
                    <% if activity.photos[0] %>
                      <a class="carousel-control-prev" href="#js-carousel-indicators-<%= activity.id %>" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                      </a>
                      <a class="carousel-control-next" href="#js-carousel-indicators-<%= activity.id %>" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                      </a>
                    <% end %>
                  </div>
                </div>
              </div>
              <div class="d-flex justify-content-center">
                <h1 id="carousel-name-tag"><%= activity.name %></h1>
              </div>
              <div class="d-flex justify-content-center">
                <%= link_to "More details", category_activity_path(:category_id, activity), class: "btn btn-secondary", id: "carousel-show-link"%>
  <!--               <button id="carousel-show-link" type="button" class="btn btn-secondary" data-dismiss="modal">Close</button> -->
            </div>
            <div id="carousel-gradient">
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/activities/new.html.erb
<div class="the-activity-container">
  <div class="new-activity-container" style="max-width:500px;">
  <br>
  <br>
  <br>
  <div class="the-title-container">
  <strong><h1>Create your activity</h1></strong>
</div>
  <br>
<%= simple_form_for [ @activity ] do |f| %>
    <%= f.input :category, as: :select, collection: Category.all, prompt: 'Select a category', label: false, :input_html => {class: 'response-project'} %>
    <%= f.input :name, :input_html => {class: 'response-project'} %>
    <%= f.input :description, as: "text", :input_html => {class: 'description'} %>
    <%= f.input :address, :input_html => {class: 'response-project'} %>
    <%= f.date_field :start_time, label: :Date, :input_html => {class: 'choose-date', id: 'choose-new-date'} %>
    <%= f.input :cover_photo, as: :file, :input_html => {class: 'upload', id: 'cover-upload'} %>
    <%= f.input :photos, as: :file, input_html: { multiple: true, class: 'upload', id: 'pictures-upload' } %>
    <br>
    <br>
    <div class="submit-images">
    <%= f.submit "Submit", class: "btn btn-primary", id: "photo-submit" %>
  <% end %>
</div>
</div>
</div>

app/views/activities/show.html.erb
<div id="show-background">
  <div class="d-flex justify-content-center">
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">

      <div class="carousel-inner">
        <% if @activity.cover_photo.attached? %>
          <div class="carousel-item active">
            <img class="index-carousel-pic" src=<%= cl_image_path(@activity.cover_photo.key,
              height: 200) %> alt="#">
          </div>
        <% end %>
        <% if @activity.photos[0] %>
          <div class="carousel-item">
            <img class="index-carousel-pic" src=<%= cl_image_path(@activity.photos[0].key,
              height: 200) %> alt="#">
          </div>
        <% end %>
        <% if @activity.photos[1] %>
          <div class="carousel-item">
            <img class="index-carousel-pic" src=<%= cl_image_path(@activity.photos[1].key,
              height: 200) %> alt="#">
          </div>
        <% end %>
        <% if @activity.photos[2] %>
          <div class="carousel-item">
            <img class="index-carousel-pic" src=<%= cl_image_path(@activity.photos[2].key,
              height: 200) %> alt="#">
          </div>
        <% end %>
      </div>
      <% if @activity.photos[0] %>
        <a class="carousel-control-prev index-carousel-control-buttons" href="#carouselExampleIndicators" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next index-carousel-control-buttons" href="#carouselExampleIndicators" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      <% end %>
      <div id="carousel-gradient">
      </div>
    </div>
  </div>

  <div class="activity-map-wrapper">

    <div class="activities-show d-flex justify-content-between align-items-center container mt-0 py-3" >
      <div class="activity-details">
        <h1><%= @activity.name %></h1>
        <%= social_share_button_tag(@activity.name) %>
        <br>
        <p class="activity-description"><%= @activity.description %></p>
        <p class="address-date"><span><%= @activity.address %></span></p>
        <p class="address-date"><span><%= DateTime.parse(@activity.start_time.to_s).strftime(("%d of %B, %Y")) %></span></p>
        <%= link_to "Join the chat!", chatroom_path(@chatroom.id), class: "btn btn-info", id: "join-chat-btn" %>
        <% if current_user %>
          <% unless current_user.bookmarks.where(activity_id: @activity.id).empty? %>
            <%= link_to 'Saved', bookmark_path(current_user.bookmarks.first), method: :delete, class: "btn btn-outline-secondary", id: "bookmark-show-buttons" %>
          <% else %>
            <%= link_to 'Save', activity_bookmark_path(activity_id: @activity), method: :post, class: "btn btn-outline-secondary", id: "bookmark-show-buttons" %>
          <% end %>
        <% else %>
          <button type="button" id="bookmark-show-buttons" class="index-save-btn btn btn-outline-secondary">Save</button>
        <% end %>
      </div>

      <div class="map-weather-wrapper">

      <a class="weatherwidget-io" href="https://forecast7.com/en/n37d81144d96/melbourne/" data-label_1="MELBOURNE" data-label_2="WEATHER" data-font="Jura" data-icons="Climacons Animated" data-mode="Current" data-theme="original" data-basecolor="" data-textcolor="#adabab" data-mooncolor="#d9cf88" data-cloudcolor="#adabab" data-cloudfill="#adabab" >MELBOURNE WEATHER</a>
      <script>
      !function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src='https://weatherwidget.io/js/widget.min.js';fjs.parentNode.insertBefore(js,fjs);}}(document,'script','weatherwidget-io-js');
      </script>

        <div id="map-wrapper">
          <div id="map"
          style="width: 400px; height: 400px; border-radius: 50%;"
          data-markers="<%= @markers.to_json %>"
          data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
          </div>

          <div class="map-info">
              <a href="https://maps.google.com/maps?ll=<%= @activity.latitude%>,<%= @activity.longitude%>&z=15&t=m&hl=en&gl=AU&mapclient=embed&daddr=<%= @activity.address%>@<%= @activity.latitude%>,<%= @activity.longitude%>" target="_blank">Directions</a>
          </div>
        </div>
      </div>
    </div>
  </div>

</div>